- project:
    check:
      jobs:
        - gophercloud-unittest
        - gophercloud-acceptance-test
    recheck-mitaka:
      jobs:
        - gophercloud-acceptance-test-mitaka
    recheck-newton:
      jobs:
        - gophercloud-acceptance-test-newton
    recheck-ocata:
      jobs:
        - gophercloud-acceptance-test-ocata
    recheck-pike:
      jobs:
        - gophercloud-acceptance-test-pike
    check-telefonica:
      jobs:
        - gophercloud-telefonica-acceptance-test
