- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - role: create-devstack-local-conf
      enable_services:
        - 'manila'
        - 'designate'
        - 'zun'
    - install-devstack
  tasks:
    - name: Run acceptance tests with gophercloud
      shell:
        cmd: |
          set -e
          echo $(export |grep OS_BRANCH)
          echo $(env |grep OS_BRANCH)
          set -o pipefail
          set -x

          go get ./... || true
          ./script/acceptancetest -v 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment:
        '{{ golang_env }}'
        OS_BRANCH: '{{ os_branch }}'
